// Generated by: python web/scripts/export-fullride-definition.py --catalog <catalog.db> --out web/src/domain/boards/definitions/kilter-fullride-7x10.generated.ts
// Scope: product 7 / layout 8 / product size 17 / sets 26,27
// Source database SHA-256: 32b2663c7e699708dc3983d6acf8eff5dd8d458530c680c50ce7f6719c61235f
// Projection: 472 scoped / 305 controllable / 167 excluded
// Do not edit by hand.

export const generatedKilterFullride7x10 = {
  "angles": [
    0,
    5,
    10,
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50,
    55,
    60,
    65,
    70
  ],
  "bounds": [
    -44,
    44,
    24,
    144
  ],
  "definitionSha256": "f0d70b3db9a607ca3929aac3a091b09ead9ea7d02451362a57073e699b849785",
  "emitted": 305,
  "emittedBySet": {
    "26": 165,
    "27": 140
  },
  "excluded": 167,
  "excludedBySet": {
    "26": 69,
    "27": 98
  },
  "placements": [
    {
      "hole_id": 3698,
      "led_id": 6145,
      "led_position": 0,
      "placement_id": 4117,
      "set_id": 26,
      "x": -40,
      "y": 28
    },
    {
      "hole_id": 3699,
      "led_id": 6146,
      "led_position": 1,
      "placement_id": 4118,
      "set_id": 26,
      "x": -40,
      "y": 36
    },
    {
      "hole_id": 3700,
      "led_id": 6147,
      "led_position": 2,
      "placement_id": 4119,
      "set_id": 26,
      "x": -40,
      "y": 44
    },
    {
      "hole_id": 3701,
      "led_id": 6148,
      "led_position": 3,
      "placement_id": 4120,
      "set_id": 26,
      "x": -40,
      "y": 52
    },
    {
      "hole_id": 3702,
      "led_id": 6149,
      "led_position": 4,
      "placement_id": 4121,
      "set_id": 26,
      "x": -40,
      "y": 60
    },
    {
      "hole_id": 3703,
      "led_id": 6150,
      "led_position": 5,
      "placement_id": 4122,
      "set_id": 26,
      "x": -40,
      "y": 68
    },
    {
      "hole_id": 3704,
      "led_id": 6151,
      "led_position": 6,
      "placement_id": 4123,
      "set_id": 26,
      "x": -40,
      "y": 76
    },
    {
      "hole_id": 3705,
      "led_id": 6152,
      "led_position": 7,
      "placement_id": 4124,
      "set_id": 26,
      "x": -40,
      "y": 84
    },
    {
      "hole_id": 3706,
      "led_id": 6153,
      "led_position": 8,
      "placement_id": 4125,
      "set_id": 26,
      "x": -40,
      "y": 92
    },
    {
      "hole_id": 3707,
      "led_id": 6154,
      "led_position": 9,
      "placement_id": 4126,
      "set_id": 26,
      "x": -40,
      "y": 100
    },
    {
      "hole_id": 3708,
      "led_id": 6155,
      "led_position": 10,
      "placement_id": 4127,
      "set_id": 26,
      "x": -40,
      "y": 108
    },
    {
      "hole_id": 3709,
      "led_id": 6156,
      "led_position": 11,
      "placement_id": 4128,
      "set_id": 26,
      "x": -40,
      "y": 116
    },
    {
      "hole_id": 3710,
      "led_id": 6157,
      "led_position": 12,
      "placement_id": 4129,
      "set_id": 26,
      "x": -40,
      "y": 124
    },
    {
      "hole_id": 3711,
      "led_id": 6158,
      "led_position": 13,
      "placement_id": 4130,
      "set_id": 26,
      "x": -40,
      "y": 132
    },
    {
      "hole_id": 3712,
      "led_id": 6159,
      "led_position": 14,
      "placement_id": 4131,
      "set_id": 26,
      "x": -40,
      "y": 140
    },
    {
      "hole_id": 3713,
      "led_id": 6160,
      "led_position": 15,
      "placement_id": 4132,
      "set_id": 27,
      "x": -36,
      "y": 136
    },
    {
      "hole_id": 3714,
      "led_id": 6161,
      "led_position": 16,
      "placement_id": 4133,
      "set_id": 27,
      "x": -36,
      "y": 128
    },
    {
      "hole_id": 3715,
      "led_id": 6162,
      "led_position": 17,
      "placement_id": 4134,
      "set_id": 27,
      "x": -36,
      "y": 120
    },
    {
      "hole_id": 3716,
      "led_id": 6163,
      "led_position": 18,
      "placement_id": 4135,
      "set_id": 27,
      "x": -36,
      "y": 112
    },
    {
      "hole_id": 3717,
      "led_id": 6164,
      "led_position": 19,
      "placement_id": 4136,
      "set_id": 27,
      "x": -36,
      "y": 104
    },
    {
      "hole_id": 3718,
      "led_id": 6165,
      "led_position": 20,
      "placement_id": 4137,
      "set_id": 27,
      "x": -36,
      "y": 96
    },
    {
      "hole_id": 3719,
      "led_id": 6166,
      "led_position": 21,
      "placement_id": 4138,
      "set_id": 27,
      "x": -36,
      "y": 88
    },
    {
      "hole_id": 3720,
      "led_id": 6167,
      "led_position": 22,
      "placement_id": 4139,
      "set_id": 27,
      "x": -36,
      "y": 80
    },
    {
      "hole_id": 3721,
      "led_id": 6168,
      "led_position": 23,
      "placement_id": 4140,
      "set_id": 27,
      "x": -36,
      "y": 72
    },
    {
      "hole_id": 3722,
      "led_id": 6169,
      "led_position": 24,
      "placement_id": 4141,
      "set_id": 27,
      "x": -36,
      "y": 64
    },
    {
      "hole_id": 3723,
      "led_id": 6170,
      "led_position": 25,
      "placement_id": 4142,
      "set_id": 27,
      "x": -36,
      "y": 56
    },
    {
      "hole_id": 3724,
      "led_id": 6171,
      "led_position": 26,
      "placement_id": 4143,
      "set_id": 27,
      "x": -36,
      "y": 48
    },
    {
      "hole_id": 3725,
      "led_id": 6172,
      "led_position": 27,
      "placement_id": 4144,
      "set_id": 27,
      "x": -36,
      "y": 40
    },
    {
      "hole_id": 3726,
      "led_id": 6173,
      "led_position": 28,
      "placement_id": 4145,
      "set_id": 27,
      "x": -36,
      "y": 32
    },
    {
      "hole_id": 3727,
      "led_id": 6174,
      "led_position": 29,
      "placement_id": 4146,
      "set_id": 26,
      "x": -32,
      "y": 28
    },
    {
      "hole_id": 3728,
      "led_id": 6175,
      "led_position": 30,
      "placement_id": 4147,
      "set_id": 26,
      "x": -32,
      "y": 36
    },
    {
      "hole_id": 3729,
      "led_id": 6176,
      "led_position": 31,
      "placement_id": 4148,
      "set_id": 26,
      "x": -32,
      "y": 44
    },
    {
      "hole_id": 3730,
      "led_id": 6177,
      "led_position": 32,
      "placement_id": 4149,
      "set_id": 26,
      "x": -32,
      "y": 52
    },
    {
      "hole_id": 3731,
      "led_id": 6178,
      "led_position": 33,
      "placement_id": 4150,
      "set_id": 26,
      "x": -32,
      "y": 60
    },
    {
      "hole_id": 3732,
      "led_id": 6179,
      "led_position": 34,
      "placement_id": 4151,
      "set_id": 26,
      "x": -32,
      "y": 68
    },
    {
      "hole_id": 3733,
      "led_id": 6180,
      "led_position": 35,
      "placement_id": 4152,
      "set_id": 26,
      "x": -32,
      "y": 76
    },
    {
      "hole_id": 3734,
      "led_id": 6181,
      "led_position": 36,
      "placement_id": 4153,
      "set_id": 26,
      "x": -32,
      "y": 84
    },
    {
      "hole_id": 3735,
      "led_id": 6182,
      "led_position": 37,
      "placement_id": 4154,
      "set_id": 26,
      "x": -32,
      "y": 92
    },
    {
      "hole_id": 3736,
      "led_id": 6183,
      "led_position": 38,
      "placement_id": 4155,
      "set_id": 26,
      "x": -32,
      "y": 100
    },
    {
      "hole_id": 3737,
      "led_id": 6184,
      "led_position": 39,
      "placement_id": 4156,
      "set_id": 26,
      "x": -32,
      "y": 108
    },
    {
      "hole_id": 3738,
      "led_id": 6185,
      "led_position": 40,
      "placement_id": 4157,
      "set_id": 26,
      "x": -32,
      "y": 116
    },
    {
      "hole_id": 3739,
      "led_id": 6186,
      "led_position": 41,
      "placement_id": 4158,
      "set_id": 26,
      "x": -32,
      "y": 124
    },
    {
      "hole_id": 3740,
      "led_id": 6187,
      "led_position": 42,
      "placement_id": 4159,
      "set_id": 26,
      "x": -32,
      "y": 132
    },
    {
      "hole_id": 3741,
      "led_id": 6188,
      "led_position": 43,
      "placement_id": 4160,
      "set_id": 26,
      "x": -32,
      "y": 140
    },
    {
      "hole_id": 3742,
      "led_id": 6189,
      "led_position": 44,
      "placement_id": 4161,
      "set_id": 27,
      "x": -28,
      "y": 136
    },
    {
      "hole_id": 3743,
      "led_id": 6190,
      "led_position": 45,
      "placement_id": 4162,
      "set_id": 27,
      "x": -28,
      "y": 128
    },
    {
      "hole_id": 3744,
      "led_id": 6191,
      "led_position": 46,
      "placement_id": 4163,
      "set_id": 27,
      "x": -28,
      "y": 120
    },
    {
      "hole_id": 3745,
      "led_id": 6192,
      "led_position": 47,
      "placement_id": 4164,
      "set_id": 27,
      "x": -28,
      "y": 112
    },
    {
      "hole_id": 3746,
      "led_id": 6193,
      "led_position": 48,
      "placement_id": 4165,
      "set_id": 27,
      "x": -28,
      "y": 104
    },
    {
      "hole_id": 3747,
      "led_id": 6194,
      "led_position": 49,
      "placement_id": 4166,
      "set_id": 27,
      "x": -28,
      "y": 96
    },
    {
      "hole_id": 3748,
      "led_id": 6195,
      "led_position": 50,
      "placement_id": 4167,
      "set_id": 27,
      "x": -28,
      "y": 88
    },
    {
      "hole_id": 3749,
      "led_id": 6196,
      "led_position": 51,
      "placement_id": 4168,
      "set_id": 27,
      "x": -28,
      "y": 80
    },
    {
      "hole_id": 3750,
      "led_id": 6197,
      "led_position": 52,
      "placement_id": 4169,
      "set_id": 27,
      "x": -28,
      "y": 72
    },
    {
      "hole_id": 3751,
      "led_id": 6198,
      "led_position": 53,
      "placement_id": 4170,
      "set_id": 27,
      "x": -28,
      "y": 64
    },
    {
      "hole_id": 3752,
      "led_id": 6199,
      "led_position": 54,
      "placement_id": 4171,
      "set_id": 27,
      "x": -28,
      "y": 56
    },
    {
      "hole_id": 3753,
      "led_id": 6200,
      "led_position": 55,
      "placement_id": 4172,
      "set_id": 27,
      "x": -28,
      "y": 48
    },
    {
      "hole_id": 3754,
      "led_id": 6201,
      "led_position": 56,
      "placement_id": 4173,
      "set_id": 27,
      "x": -28,
      "y": 40
    },
    {
      "hole_id": 3755,
      "led_id": 6202,
      "led_position": 57,
      "placement_id": 4174,
      "set_id": 27,
      "x": -28,
      "y": 32
    },
    {
      "hole_id": 3756,
      "led_id": 6203,
      "led_position": 58,
      "placement_id": 4175,
      "set_id": 26,
      "x": -24,
      "y": 28
    },
    {
      "hole_id": 3757,
      "led_id": 6204,
      "led_position": 59,
      "placement_id": 4176,
      "set_id": 26,
      "x": -24,
      "y": 36
    },
    {
      "hole_id": 3758,
      "led_id": 6205,
      "led_position": 60,
      "placement_id": 4177,
      "set_id": 26,
      "x": -24,
      "y": 44
    },
    {
      "hole_id": 3759,
      "led_id": 6206,
      "led_position": 61,
      "placement_id": 4178,
      "set_id": 26,
      "x": -24,
      "y": 52
    },
    {
      "hole_id": 3760,
      "led_id": 6207,
      "led_position": 62,
      "placement_id": 4179,
      "set_id": 26,
      "x": -24,
      "y": 60
    },
    {
      "hole_id": 3761,
      "led_id": 6208,
      "led_position": 63,
      "placement_id": 4180,
      "set_id": 26,
      "x": -24,
      "y": 68
    },
    {
      "hole_id": 3762,
      "led_id": 6209,
      "led_position": 64,
      "placement_id": 4181,
      "set_id": 26,
      "x": -24,
      "y": 76
    },
    {
      "hole_id": 3763,
      "led_id": 6210,
      "led_position": 65,
      "placement_id": 4182,
      "set_id": 26,
      "x": -24,
      "y": 84
    },
    {
      "hole_id": 3764,
      "led_id": 6211,
      "led_position": 66,
      "placement_id": 4183,
      "set_id": 26,
      "x": -24,
      "y": 92
    },
    {
      "hole_id": 3765,
      "led_id": 6212,
      "led_position": 67,
      "placement_id": 4184,
      "set_id": 26,
      "x": -24,
      "y": 100
    },
    {
      "hole_id": 3766,
      "led_id": 6213,
      "led_position": 68,
      "placement_id": 4185,
      "set_id": 26,
      "x": -24,
      "y": 108
    },
    {
      "hole_id": 3767,
      "led_id": 6214,
      "led_position": 69,
      "placement_id": 4186,
      "set_id": 26,
      "x": -24,
      "y": 116
    },
    {
      "hole_id": 3768,
      "led_id": 6215,
      "led_position": 70,
      "placement_id": 4187,
      "set_id": 26,
      "x": -24,
      "y": 124
    },
    {
      "hole_id": 3769,
      "led_id": 6216,
      "led_position": 71,
      "placement_id": 4188,
      "set_id": 26,
      "x": -24,
      "y": 132
    },
    {
      "hole_id": 3770,
      "led_id": 6217,
      "led_position": 72,
      "placement_id": 4189,
      "set_id": 26,
      "x": -24,
      "y": 140
    },
    {
      "hole_id": 3771,
      "led_id": 6218,
      "led_position": 73,
      "placement_id": 4190,
      "set_id": 27,
      "x": -20,
      "y": 136
    },
    {
      "hole_id": 3772,
      "led_id": 6219,
      "led_position": 74,
      "placement_id": 4191,
      "set_id": 27,
      "x": -20,
      "y": 128
    },
    {
      "hole_id": 3773,
      "led_id": 6220,
      "led_position": 75,
      "placement_id": 4192,
      "set_id": 27,
      "x": -20,
      "y": 120
    },
    {
      "hole_id": 3774,
      "led_id": 6221,
      "led_position": 76,
      "placement_id": 4193,
      "set_id": 27,
      "x": -20,
      "y": 112
    },
    {
      "hole_id": 3775,
      "led_id": 6222,
      "led_position": 77,
      "placement_id": 4194,
      "set_id": 27,
      "x": -20,
      "y": 104
    },
    {
      "hole_id": 3776,
      "led_id": 6223,
      "led_position": 78,
      "placement_id": 4195,
      "set_id": 27,
      "x": -20,
      "y": 96
    },
    {
      "hole_id": 3777,
      "led_id": 6224,
      "led_position": 79,
      "placement_id": 4196,
      "set_id": 27,
      "x": -20,
      "y": 88
    },
    {
      "hole_id": 3778,
      "led_id": 6225,
      "led_position": 80,
      "placement_id": 4197,
      "set_id": 27,
      "x": -20,
      "y": 80
    },
    {
      "hole_id": 3779,
      "led_id": 6226,
      "led_position": 81,
      "placement_id": 4198,
      "set_id": 27,
      "x": -20,
      "y": 72
    },
    {
      "hole_id": 3780,
      "led_id": 6227,
      "led_position": 82,
      "placement_id": 4199,
      "set_id": 27,
      "x": -20,
      "y": 64
    },
    {
      "hole_id": 3781,
      "led_id": 6228,
      "led_position": 83,
      "placement_id": 4200,
      "set_id": 27,
      "x": -20,
      "y": 56
    },
    {
      "hole_id": 3782,
      "led_id": 6229,
      "led_position": 84,
      "placement_id": 4201,
      "set_id": 27,
      "x": -20,
      "y": 48
    },
    {
      "hole_id": 3783,
      "led_id": 6230,
      "led_position": 85,
      "placement_id": 4202,
      "set_id": 27,
      "x": -20,
      "y": 40
    },
    {
      "hole_id": 3784,
      "led_id": 6231,
      "led_position": 86,
      "placement_id": 4203,
      "set_id": 27,
      "x": -20,
      "y": 32
    },
    {
      "hole_id": 3785,
      "led_id": 6232,
      "led_position": 87,
      "placement_id": 4204,
      "set_id": 26,
      "x": -16,
      "y": 28
    },
    {
      "hole_id": 3786,
      "led_id": 6233,
      "led_position": 88,
      "placement_id": 4205,
      "set_id": 26,
      "x": -16,
      "y": 36
    },
    {
      "hole_id": 3787,
      "led_id": 6234,
      "led_position": 89,
      "placement_id": 4206,
      "set_id": 26,
      "x": -16,
      "y": 44
    },
    {
      "hole_id": 3788,
      "led_id": 6235,
      "led_position": 90,
      "placement_id": 4207,
      "set_id": 26,
      "x": -16,
      "y": 52
    },
    {
      "hole_id": 3789,
      "led_id": 6236,
      "led_position": 91,
      "placement_id": 4208,
      "set_id": 26,
      "x": -16,
      "y": 60
    },
    {
      "hole_id": 3790,
      "led_id": 6237,
      "led_position": 92,
      "placement_id": 4209,
      "set_id": 26,
      "x": -16,
      "y": 68
    },
    {
      "hole_id": 3791,
      "led_id": 6238,
      "led_position": 93,
      "placement_id": 4210,
      "set_id": 26,
      "x": -16,
      "y": 76
    },
    {
      "hole_id": 3792,
      "led_id": 6239,
      "led_position": 94,
      "placement_id": 4211,
      "set_id": 26,
      "x": -16,
      "y": 84
    },
    {
      "hole_id": 3793,
      "led_id": 6240,
      "led_position": 95,
      "placement_id": 4212,
      "set_id": 26,
      "x": -16,
      "y": 92
    },
    {
      "hole_id": 3794,
      "led_id": 6241,
      "led_position": 96,
      "placement_id": 4213,
      "set_id": 26,
      "x": -16,
      "y": 100
    },
    {
      "hole_id": 3795,
      "led_id": 6242,
      "led_position": 97,
      "placement_id": 4214,
      "set_id": 26,
      "x": -16,
      "y": 108
    },
    {
      "hole_id": 3796,
      "led_id": 6243,
      "led_position": 98,
      "placement_id": 4215,
      "set_id": 26,
      "x": -16,
      "y": 116
    },
    {
      "hole_id": 3797,
      "led_id": 6244,
      "led_position": 99,
      "placement_id": 4216,
      "set_id": 26,
      "x": -16,
      "y": 124
    },
    {
      "hole_id": 3798,
      "led_id": 6245,
      "led_position": 100,
      "placement_id": 4217,
      "set_id": 26,
      "x": -16,
      "y": 132
    },
    {
      "hole_id": 3799,
      "led_id": 6246,
      "led_position": 101,
      "placement_id": 4218,
      "set_id": 26,
      "x": -16,
      "y": 140
    },
    {
      "hole_id": 3800,
      "led_id": 6247,
      "led_position": 102,
      "placement_id": 4219,
      "set_id": 27,
      "x": -12,
      "y": 136
    },
    {
      "hole_id": 3801,
      "led_id": 6248,
      "led_position": 103,
      "placement_id": 4220,
      "set_id": 27,
      "x": -12,
      "y": 128
    },
    {
      "hole_id": 3802,
      "led_id": 6249,
      "led_position": 104,
      "placement_id": 4221,
      "set_id": 27,
      "x": -12,
      "y": 120
    },
    {
      "hole_id": 3803,
      "led_id": 6250,
      "led_position": 105,
      "placement_id": 4222,
      "set_id": 27,
      "x": -12,
      "y": 112
    },
    {
      "hole_id": 3804,
      "led_id": 6251,
      "led_position": 106,
      "placement_id": 4223,
      "set_id": 27,
      "x": -12,
      "y": 104
    },
    {
      "hole_id": 3805,
      "led_id": 6252,
      "led_position": 107,
      "placement_id": 4224,
      "set_id": 27,
      "x": -12,
      "y": 96
    },
    {
      "hole_id": 3806,
      "led_id": 6253,
      "led_position": 108,
      "placement_id": 4225,
      "set_id": 27,
      "x": -12,
      "y": 88
    },
    {
      "hole_id": 3807,
      "led_id": 6254,
      "led_position": 109,
      "placement_id": 4226,
      "set_id": 27,
      "x": -12,
      "y": 80
    },
    {
      "hole_id": 3808,
      "led_id": 6255,
      "led_position": 110,
      "placement_id": 4227,
      "set_id": 27,
      "x": -12,
      "y": 72
    },
    {
      "hole_id": 3809,
      "led_id": 6256,
      "led_position": 111,
      "placement_id": 4228,
      "set_id": 27,
      "x": -12,
      "y": 64
    },
    {
      "hole_id": 3810,
      "led_id": 6257,
      "led_position": 112,
      "placement_id": 4229,
      "set_id": 27,
      "x": -12,
      "y": 56
    },
    {
      "hole_id": 3811,
      "led_id": 6258,
      "led_position": 113,
      "placement_id": 4230,
      "set_id": 27,
      "x": -12,
      "y": 48
    },
    {
      "hole_id": 3812,
      "led_id": 6259,
      "led_position": 114,
      "placement_id": 4231,
      "set_id": 27,
      "x": -12,
      "y": 40
    },
    {
      "hole_id": 3813,
      "led_id": 6260,
      "led_position": 115,
      "placement_id": 4232,
      "set_id": 27,
      "x": -12,
      "y": 32
    },
    {
      "hole_id": 3814,
      "led_id": 6261,
      "led_position": 116,
      "placement_id": 4233,
      "set_id": 26,
      "x": -8,
      "y": 28
    },
    {
      "hole_id": 3815,
      "led_id": 6262,
      "led_position": 117,
      "placement_id": 4234,
      "set_id": 26,
      "x": -8,
      "y": 36
    },
    {
      "hole_id": 3816,
      "led_id": 6263,
      "led_position": 118,
      "placement_id": 4235,
      "set_id": 26,
      "x": -8,
      "y": 44
    },
    {
      "hole_id": 3817,
      "led_id": 6264,
      "led_position": 119,
      "placement_id": 4236,
      "set_id": 26,
      "x": -8,
      "y": 52
    },
    {
      "hole_id": 3818,
      "led_id": 6265,
      "led_position": 120,
      "placement_id": 4237,
      "set_id": 26,
      "x": -8,
      "y": 60
    },
    {
      "hole_id": 3819,
      "led_id": 6266,
      "led_position": 121,
      "placement_id": 4238,
      "set_id": 26,
      "x": -8,
      "y": 68
    },
    {
      "hole_id": 3820,
      "led_id": 6267,
      "led_position": 122,
      "placement_id": 4239,
      "set_id": 26,
      "x": -8,
      "y": 76
    },
    {
      "hole_id": 3821,
      "led_id": 6268,
      "led_position": 123,
      "placement_id": 4240,
      "set_id": 26,
      "x": -8,
      "y": 84
    },
    {
      "hole_id": 3822,
      "led_id": 6269,
      "led_position": 124,
      "placement_id": 4241,
      "set_id": 26,
      "x": -8,
      "y": 92
    },
    {
      "hole_id": 3823,
      "led_id": 6270,
      "led_position": 125,
      "placement_id": 4242,
      "set_id": 26,
      "x": -8,
      "y": 100
    },
    {
      "hole_id": 3824,
      "led_id": 6271,
      "led_position": 126,
      "placement_id": 4243,
      "set_id": 26,
      "x": -8,
      "y": 108
    },
    {
      "hole_id": 3825,
      "led_id": 6272,
      "led_position": 127,
      "placement_id": 4244,
      "set_id": 26,
      "x": -8,
      "y": 116
    },
    {
      "hole_id": 3826,
      "led_id": 6273,
      "led_position": 128,
      "placement_id": 4245,
      "set_id": 26,
      "x": -8,
      "y": 124
    },
    {
      "hole_id": 3827,
      "led_id": 6274,
      "led_position": 129,
      "placement_id": 4246,
      "set_id": 26,
      "x": -8,
      "y": 132
    },
    {
      "hole_id": 3828,
      "led_id": 6275,
      "led_position": 130,
      "placement_id": 4247,
      "set_id": 26,
      "x": -8,
      "y": 140
    },
    {
      "hole_id": 3829,
      "led_id": 6276,
      "led_position": 131,
      "placement_id": 4248,
      "set_id": 27,
      "x": -4,
      "y": 136
    },
    {
      "hole_id": 3830,
      "led_id": 6277,
      "led_position": 132,
      "placement_id": 4249,
      "set_id": 27,
      "x": -4,
      "y": 128
    },
    {
      "hole_id": 3831,
      "led_id": 6278,
      "led_position": 133,
      "placement_id": 4250,
      "set_id": 27,
      "x": -4,
      "y": 120
    },
    {
      "hole_id": 3832,
      "led_id": 6279,
      "led_position": 134,
      "placement_id": 4251,
      "set_id": 27,
      "x": -4,
      "y": 112
    },
    {
      "hole_id": 3833,
      "led_id": 6280,
      "led_position": 135,
      "placement_id": 4252,
      "set_id": 27,
      "x": -4,
      "y": 104
    },
    {
      "hole_id": 3834,
      "led_id": 6281,
      "led_position": 136,
      "placement_id": 4253,
      "set_id": 27,
      "x": -4,
      "y": 96
    },
    {
      "hole_id": 3835,
      "led_id": 6282,
      "led_position": 137,
      "placement_id": 4254,
      "set_id": 27,
      "x": -4,
      "y": 88
    },
    {
      "hole_id": 3836,
      "led_id": 6283,
      "led_position": 138,
      "placement_id": 4255,
      "set_id": 27,
      "x": -4,
      "y": 80
    },
    {
      "hole_id": 3837,
      "led_id": 6284,
      "led_position": 139,
      "placement_id": 4256,
      "set_id": 27,
      "x": -4,
      "y": 72
    },
    {
      "hole_id": 3838,
      "led_id": 6285,
      "led_position": 140,
      "placement_id": 4257,
      "set_id": 27,
      "x": -4,
      "y": 64
    },
    {
      "hole_id": 3839,
      "led_id": 6286,
      "led_position": 141,
      "placement_id": 4258,
      "set_id": 27,
      "x": -4,
      "y": 56
    },
    {
      "hole_id": 3840,
      "led_id": 6287,
      "led_position": 142,
      "placement_id": 4259,
      "set_id": 27,
      "x": -4,
      "y": 48
    },
    {
      "hole_id": 3841,
      "led_id": 6288,
      "led_position": 143,
      "placement_id": 4260,
      "set_id": 27,
      "x": -4,
      "y": 40
    },
    {
      "hole_id": 3842,
      "led_id": 6289,
      "led_position": 144,
      "placement_id": 4261,
      "set_id": 27,
      "x": -4,
      "y": 32
    },
    {
      "hole_id": 3843,
      "led_id": 6290,
      "led_position": 145,
      "placement_id": 4262,
      "set_id": 26,
      "x": 0,
      "y": 28
    },
    {
      "hole_id": 3844,
      "led_id": 6291,
      "led_position": 146,
      "placement_id": 4263,
      "set_id": 26,
      "x": 0,
      "y": 36
    },
    {
      "hole_id": 3845,
      "led_id": 6292,
      "led_position": 147,
      "placement_id": 4264,
      "set_id": 26,
      "x": 0,
      "y": 44
    },
    {
      "hole_id": 3846,
      "led_id": 6293,
      "led_position": 148,
      "placement_id": 4265,
      "set_id": 26,
      "x": 0,
      "y": 52
    },
    {
      "hole_id": 3847,
      "led_id": 6294,
      "led_position": 149,
      "placement_id": 4266,
      "set_id": 26,
      "x": 0,
      "y": 60
    },
    {
      "hole_id": 3848,
      "led_id": 6295,
      "led_position": 150,
      "placement_id": 4267,
      "set_id": 26,
      "x": 0,
      "y": 68
    },
    {
      "hole_id": 3849,
      "led_id": 6296,
      "led_position": 151,
      "placement_id": 4268,
      "set_id": 26,
      "x": 0,
      "y": 76
    },
    {
      "hole_id": 3850,
      "led_id": 6297,
      "led_position": 152,
      "placement_id": 4269,
      "set_id": 26,
      "x": 0,
      "y": 84
    },
    {
      "hole_id": 3851,
      "led_id": 6298,
      "led_position": 153,
      "placement_id": 4270,
      "set_id": 26,
      "x": 0,
      "y": 92
    },
    {
      "hole_id": 3852,
      "led_id": 6299,
      "led_position": 154,
      "placement_id": 4271,
      "set_id": 26,
      "x": 0,
      "y": 100
    },
    {
      "hole_id": 3853,
      "led_id": 6300,
      "led_position": 155,
      "placement_id": 4272,
      "set_id": 26,
      "x": 0,
      "y": 108
    },
    {
      "hole_id": 3854,
      "led_id": 6301,
      "led_position": 156,
      "placement_id": 4273,
      "set_id": 26,
      "x": 0,
      "y": 116
    },
    {
      "hole_id": 3855,
      "led_id": 6302,
      "led_position": 157,
      "placement_id": 4274,
      "set_id": 26,
      "x": 0,
      "y": 124
    },
    {
      "hole_id": 3856,
      "led_id": 6303,
      "led_position": 158,
      "placement_id": 4275,
      "set_id": 26,
      "x": 0,
      "y": 132
    },
    {
      "hole_id": 3857,
      "led_id": 6304,
      "led_position": 159,
      "placement_id": 4276,
      "set_id": 26,
      "x": 0,
      "y": 140
    },
    {
      "hole_id": 3858,
      "led_id": 6305,
      "led_position": 160,
      "placement_id": 4277,
      "set_id": 27,
      "x": 4,
      "y": 136
    },
    {
      "hole_id": 3859,
      "led_id": 6306,
      "led_position": 161,
      "placement_id": 4278,
      "set_id": 27,
      "x": 4,
      "y": 128
    },
    {
      "hole_id": 3860,
      "led_id": 6307,
      "led_position": 162,
      "placement_id": 4279,
      "set_id": 27,
      "x": 4,
      "y": 120
    },
    {
      "hole_id": 3861,
      "led_id": 6308,
      "led_position": 163,
      "placement_id": 4280,
      "set_id": 27,
      "x": 4,
      "y": 112
    },
    {
      "hole_id": 3862,
      "led_id": 6309,
      "led_position": 164,
      "placement_id": 4281,
      "set_id": 27,
      "x": 4,
      "y": 104
    },
    {
      "hole_id": 3863,
      "led_id": 6310,
      "led_position": 165,
      "placement_id": 4282,
      "set_id": 27,
      "x": 4,
      "y": 96
    },
    {
      "hole_id": 3864,
      "led_id": 6311,
      "led_position": 166,
      "placement_id": 4283,
      "set_id": 27,
      "x": 4,
      "y": 88
    },
    {
      "hole_id": 3865,
      "led_id": 6312,
      "led_position": 167,
      "placement_id": 4284,
      "set_id": 27,
      "x": 4,
      "y": 80
    },
    {
      "hole_id": 3866,
      "led_id": 6313,
      "led_position": 168,
      "placement_id": 4285,
      "set_id": 27,
      "x": 4,
      "y": 72
    },
    {
      "hole_id": 3867,
      "led_id": 6314,
      "led_position": 169,
      "placement_id": 4286,
      "set_id": 27,
      "x": 4,
      "y": 64
    },
    {
      "hole_id": 3868,
      "led_id": 6315,
      "led_position": 170,
      "placement_id": 4287,
      "set_id": 27,
      "x": 4,
      "y": 56
    },
    {
      "hole_id": 3869,
      "led_id": 6316,
      "led_position": 171,
      "placement_id": 4288,
      "set_id": 27,
      "x": 4,
      "y": 48
    },
    {
      "hole_id": 3870,
      "led_id": 6317,
      "led_position": 172,
      "placement_id": 4289,
      "set_id": 27,
      "x": 4,
      "y": 40
    },
    {
      "hole_id": 3871,
      "led_id": 6318,
      "led_position": 173,
      "placement_id": 4290,
      "set_id": 27,
      "x": 4,
      "y": 32
    },
    {
      "hole_id": 3872,
      "led_id": 6319,
      "led_position": 174,
      "placement_id": 4291,
      "set_id": 26,
      "x": 8,
      "y": 28
    },
    {
      "hole_id": 3873,
      "led_id": 6320,
      "led_position": 175,
      "placement_id": 4292,
      "set_id": 26,
      "x": 8,
      "y": 36
    },
    {
      "hole_id": 3874,
      "led_id": 6321,
      "led_position": 176,
      "placement_id": 4293,
      "set_id": 26,
      "x": 8,
      "y": 44
    },
    {
      "hole_id": 3875,
      "led_id": 6322,
      "led_position": 177,
      "placement_id": 4294,
      "set_id": 26,
      "x": 8,
      "y": 52
    },
    {
      "hole_id": 3876,
      "led_id": 6323,
      "led_position": 178,
      "placement_id": 4295,
      "set_id": 26,
      "x": 8,
      "y": 60
    },
    {
      "hole_id": 3877,
      "led_id": 6324,
      "led_position": 179,
      "placement_id": 4296,
      "set_id": 26,
      "x": 8,
      "y": 68
    },
    {
      "hole_id": 3878,
      "led_id": 6325,
      "led_position": 180,
      "placement_id": 4297,
      "set_id": 26,
      "x": 8,
      "y": 76
    },
    {
      "hole_id": 3879,
      "led_id": 6326,
      "led_position": 181,
      "placement_id": 4298,
      "set_id": 26,
      "x": 8,
      "y": 84
    },
    {
      "hole_id": 3880,
      "led_id": 6327,
      "led_position": 182,
      "placement_id": 4299,
      "set_id": 26,
      "x": 8,
      "y": 92
    },
    {
      "hole_id": 3881,
      "led_id": 6328,
      "led_position": 183,
      "placement_id": 4300,
      "set_id": 26,
      "x": 8,
      "y": 100
    },
    {
      "hole_id": 3882,
      "led_id": 6329,
      "led_position": 184,
      "placement_id": 4301,
      "set_id": 26,
      "x": 8,
      "y": 108
    },
    {
      "hole_id": 3883,
      "led_id": 6330,
      "led_position": 185,
      "placement_id": 4302,
      "set_id": 26,
      "x": 8,
      "y": 116
    },
    {
      "hole_id": 3884,
      "led_id": 6331,
      "led_position": 186,
      "placement_id": 4303,
      "set_id": 26,
      "x": 8,
      "y": 124
    },
    {
      "hole_id": 3885,
      "led_id": 6332,
      "led_position": 187,
      "placement_id": 4304,
      "set_id": 26,
      "x": 8,
      "y": 132
    },
    {
      "hole_id": 3886,
      "led_id": 6333,
      "led_position": 188,
      "placement_id": 4305,
      "set_id": 26,
      "x": 8,
      "y": 140
    },
    {
      "hole_id": 3887,
      "led_id": 6334,
      "led_position": 189,
      "placement_id": 4306,
      "set_id": 27,
      "x": 12,
      "y": 136
    },
    {
      "hole_id": 3888,
      "led_id": 6335,
      "led_position": 190,
      "placement_id": 4307,
      "set_id": 27,
      "x": 12,
      "y": 128
    },
    {
      "hole_id": 3889,
      "led_id": 6336,
      "led_position": 191,
      "placement_id": 4308,
      "set_id": 27,
      "x": 12,
      "y": 120
    },
    {
      "hole_id": 3890,
      "led_id": 6337,
      "led_position": 192,
      "placement_id": 4309,
      "set_id": 27,
      "x": 12,
      "y": 112
    },
    {
      "hole_id": 3891,
      "led_id": 6338,
      "led_position": 193,
      "placement_id": 4310,
      "set_id": 27,
      "x": 12,
      "y": 104
    },
    {
      "hole_id": 3892,
      "led_id": 6339,
      "led_position": 194,
      "placement_id": 4311,
      "set_id": 27,
      "x": 12,
      "y": 96
    },
    {
      "hole_id": 3893,
      "led_id": 6340,
      "led_position": 195,
      "placement_id": 4312,
      "set_id": 27,
      "x": 12,
      "y": 88
    },
    {
      "hole_id": 3894,
      "led_id": 6341,
      "led_position": 196,
      "placement_id": 4313,
      "set_id": 27,
      "x": 12,
      "y": 80
    },
    {
      "hole_id": 3895,
      "led_id": 6342,
      "led_position": 197,
      "placement_id": 4314,
      "set_id": 27,
      "x": 12,
      "y": 72
    },
    {
      "hole_id": 3896,
      "led_id": 6343,
      "led_position": 198,
      "placement_id": 4315,
      "set_id": 27,
      "x": 12,
      "y": 64
    },
    {
      "hole_id": 3897,
      "led_id": 6344,
      "led_position": 199,
      "placement_id": 4316,
      "set_id": 27,
      "x": 12,
      "y": 56
    },
    {
      "hole_id": 3898,
      "led_id": 6345,
      "led_position": 200,
      "placement_id": 4317,
      "set_id": 27,
      "x": 12,
      "y": 48
    },
    {
      "hole_id": 3899,
      "led_id": 6346,
      "led_position": 201,
      "placement_id": 4318,
      "set_id": 27,
      "x": 12,
      "y": 40
    },
    {
      "hole_id": 3900,
      "led_id": 6347,
      "led_position": 202,
      "placement_id": 4319,
      "set_id": 27,
      "x": 12,
      "y": 32
    },
    {
      "hole_id": 3901,
      "led_id": 6348,
      "led_position": 203,
      "placement_id": 4320,
      "set_id": 26,
      "x": 16,
      "y": 28
    },
    {
      "hole_id": 3902,
      "led_id": 6349,
      "led_position": 204,
      "placement_id": 4321,
      "set_id": 26,
      "x": 16,
      "y": 36
    },
    {
      "hole_id": 3903,
      "led_id": 6350,
      "led_position": 205,
      "placement_id": 4322,
      "set_id": 26,
      "x": 16,
      "y": 44
    },
    {
      "hole_id": 3904,
      "led_id": 6351,
      "led_position": 206,
      "placement_id": 4323,
      "set_id": 26,
      "x": 16,
      "y": 52
    },
    {
      "hole_id": 3905,
      "led_id": 6352,
      "led_position": 207,
      "placement_id": 4324,
      "set_id": 26,
      "x": 16,
      "y": 60
    },
    {
      "hole_id": 3906,
      "led_id": 6353,
      "led_position": 208,
      "placement_id": 4325,
      "set_id": 26,
      "x": 16,
      "y": 68
    },
    {
      "hole_id": 3907,
      "led_id": 6354,
      "led_position": 209,
      "placement_id": 4326,
      "set_id": 26,
      "x": 16,
      "y": 76
    },
    {
      "hole_id": 3908,
      "led_id": 6355,
      "led_position": 210,
      "placement_id": 4327,
      "set_id": 26,
      "x": 16,
      "y": 84
    },
    {
      "hole_id": 3909,
      "led_id": 6356,
      "led_position": 211,
      "placement_id": 4328,
      "set_id": 26,
      "x": 16,
      "y": 92
    },
    {
      "hole_id": 3910,
      "led_id": 6357,
      "led_position": 212,
      "placement_id": 4329,
      "set_id": 26,
      "x": 16,
      "y": 100
    },
    {
      "hole_id": 3911,
      "led_id": 6358,
      "led_position": 213,
      "placement_id": 4330,
      "set_id": 26,
      "x": 16,
      "y": 108
    },
    {
      "hole_id": 3912,
      "led_id": 6359,
      "led_position": 214,
      "placement_id": 4331,
      "set_id": 26,
      "x": 16,
      "y": 116
    },
    {
      "hole_id": 3913,
      "led_id": 6360,
      "led_position": 215,
      "placement_id": 4332,
      "set_id": 26,
      "x": 16,
      "y": 124
    },
    {
      "hole_id": 3914,
      "led_id": 6361,
      "led_position": 216,
      "placement_id": 4333,
      "set_id": 26,
      "x": 16,
      "y": 132
    },
    {
      "hole_id": 3915,
      "led_id": 6362,
      "led_position": 217,
      "placement_id": 4334,
      "set_id": 26,
      "x": 16,
      "y": 140
    },
    {
      "hole_id": 3916,
      "led_id": 6363,
      "led_position": 218,
      "placement_id": 4335,
      "set_id": 27,
      "x": 20,
      "y": 136
    },
    {
      "hole_id": 3917,
      "led_id": 6364,
      "led_position": 219,
      "placement_id": 4336,
      "set_id": 27,
      "x": 20,
      "y": 128
    },
    {
      "hole_id": 3918,
      "led_id": 6365,
      "led_position": 220,
      "placement_id": 4337,
      "set_id": 27,
      "x": 20,
      "y": 120
    },
    {
      "hole_id": 3919,
      "led_id": 6366,
      "led_position": 221,
      "placement_id": 4338,
      "set_id": 27,
      "x": 20,
      "y": 112
    },
    {
      "hole_id": 3920,
      "led_id": 6367,
      "led_position": 222,
      "placement_id": 4339,
      "set_id": 27,
      "x": 20,
      "y": 104
    },
    {
      "hole_id": 3921,
      "led_id": 6368,
      "led_position": 223,
      "placement_id": 4340,
      "set_id": 27,
      "x": 20,
      "y": 96
    },
    {
      "hole_id": 3922,
      "led_id": 6369,
      "led_position": 224,
      "placement_id": 4341,
      "set_id": 27,
      "x": 20,
      "y": 88
    },
    {
      "hole_id": 3923,
      "led_id": 6370,
      "led_position": 225,
      "placement_id": 4342,
      "set_id": 27,
      "x": 20,
      "y": 80
    },
    {
      "hole_id": 3924,
      "led_id": 6371,
      "led_position": 226,
      "placement_id": 4343,
      "set_id": 27,
      "x": 20,
      "y": 72
    },
    {
      "hole_id": 3925,
      "led_id": 6372,
      "led_position": 227,
      "placement_id": 4344,
      "set_id": 27,
      "x": 20,
      "y": 64
    },
    {
      "hole_id": 3926,
      "led_id": 6373,
      "led_position": 228,
      "placement_id": 4345,
      "set_id": 27,
      "x": 20,
      "y": 56
    },
    {
      "hole_id": 3927,
      "led_id": 6374,
      "led_position": 229,
      "placement_id": 4346,
      "set_id": 27,
      "x": 20,
      "y": 48
    },
    {
      "hole_id": 3928,
      "led_id": 6375,
      "led_position": 230,
      "placement_id": 4347,
      "set_id": 27,
      "x": 20,
      "y": 40
    },
    {
      "hole_id": 3929,
      "led_id": 6376,
      "led_position": 231,
      "placement_id": 4348,
      "set_id": 27,
      "x": 20,
      "y": 32
    },
    {
      "hole_id": 3930,
      "led_id": 6377,
      "led_position": 232,
      "placement_id": 4349,
      "set_id": 26,
      "x": 24,
      "y": 28
    },
    {
      "hole_id": 3931,
      "led_id": 6378,
      "led_position": 233,
      "placement_id": 4350,
      "set_id": 26,
      "x": 24,
      "y": 36
    },
    {
      "hole_id": 3932,
      "led_id": 6379,
      "led_position": 234,
      "placement_id": 4351,
      "set_id": 26,
      "x": 24,
      "y": 44
    },
    {
      "hole_id": 3933,
      "led_id": 6380,
      "led_position": 235,
      "placement_id": 4352,
      "set_id": 26,
      "x": 24,
      "y": 52
    },
    {
      "hole_id": 3934,
      "led_id": 6381,
      "led_position": 236,
      "placement_id": 4353,
      "set_id": 26,
      "x": 24,
      "y": 60
    },
    {
      "hole_id": 3935,
      "led_id": 6382,
      "led_position": 237,
      "placement_id": 4354,
      "set_id": 26,
      "x": 24,
      "y": 68
    },
    {
      "hole_id": 3936,
      "led_id": 6383,
      "led_position": 238,
      "placement_id": 4355,
      "set_id": 26,
      "x": 24,
      "y": 76
    },
    {
      "hole_id": 3937,
      "led_id": 6384,
      "led_position": 239,
      "placement_id": 4356,
      "set_id": 26,
      "x": 24,
      "y": 84
    },
    {
      "hole_id": 3938,
      "led_id": 6385,
      "led_position": 240,
      "placement_id": 4357,
      "set_id": 26,
      "x": 24,
      "y": 92
    },
    {
      "hole_id": 3939,
      "led_id": 6386,
      "led_position": 241,
      "placement_id": 4358,
      "set_id": 26,
      "x": 24,
      "y": 100
    },
    {
      "hole_id": 3940,
      "led_id": 6387,
      "led_position": 242,
      "placement_id": 4359,
      "set_id": 26,
      "x": 24,
      "y": 108
    },
    {
      "hole_id": 3941,
      "led_id": 6388,
      "led_position": 243,
      "placement_id": 4360,
      "set_id": 26,
      "x": 24,
      "y": 116
    },
    {
      "hole_id": 3942,
      "led_id": 6389,
      "led_position": 244,
      "placement_id": 4361,
      "set_id": 26,
      "x": 24,
      "y": 124
    },
    {
      "hole_id": 3943,
      "led_id": 6390,
      "led_position": 245,
      "placement_id": 4362,
      "set_id": 26,
      "x": 24,
      "y": 132
    },
    {
      "hole_id": 3944,
      "led_id": 6391,
      "led_position": 246,
      "placement_id": 4363,
      "set_id": 26,
      "x": 24,
      "y": 140
    },
    {
      "hole_id": 3945,
      "led_id": 6392,
      "led_position": 247,
      "placement_id": 4364,
      "set_id": 27,
      "x": 28,
      "y": 136
    },
    {
      "hole_id": 3946,
      "led_id": 6393,
      "led_position": 248,
      "placement_id": 4365,
      "set_id": 27,
      "x": 28,
      "y": 128
    },
    {
      "hole_id": 3947,
      "led_id": 6394,
      "led_position": 249,
      "placement_id": 4366,
      "set_id": 27,
      "x": 28,
      "y": 120
    },
    {
      "hole_id": 3948,
      "led_id": 6395,
      "led_position": 250,
      "placement_id": 4367,
      "set_id": 27,
      "x": 28,
      "y": 112
    },
    {
      "hole_id": 3949,
      "led_id": 6396,
      "led_position": 251,
      "placement_id": 4368,
      "set_id": 27,
      "x": 28,
      "y": 104
    },
    {
      "hole_id": 3950,
      "led_id": 6397,
      "led_position": 252,
      "placement_id": 4369,
      "set_id": 27,
      "x": 28,
      "y": 96
    },
    {
      "hole_id": 3951,
      "led_id": 6398,
      "led_position": 253,
      "placement_id": 4370,
      "set_id": 27,
      "x": 28,
      "y": 88
    },
    {
      "hole_id": 3952,
      "led_id": 6399,
      "led_position": 254,
      "placement_id": 4371,
      "set_id": 27,
      "x": 28,
      "y": 80
    },
    {
      "hole_id": 3953,
      "led_id": 6400,
      "led_position": 255,
      "placement_id": 4372,
      "set_id": 27,
      "x": 28,
      "y": 72
    },
    {
      "hole_id": 3954,
      "led_id": 6401,
      "led_position": 256,
      "placement_id": 4373,
      "set_id": 27,
      "x": 28,
      "y": 64
    },
    {
      "hole_id": 3955,
      "led_id": 6402,
      "led_position": 257,
      "placement_id": 4374,
      "set_id": 27,
      "x": 28,
      "y": 56
    },
    {
      "hole_id": 3956,
      "led_id": 6403,
      "led_position": 258,
      "placement_id": 4375,
      "set_id": 27,
      "x": 28,
      "y": 48
    },
    {
      "hole_id": 3957,
      "led_id": 6404,
      "led_position": 259,
      "placement_id": 4376,
      "set_id": 27,
      "x": 28,
      "y": 40
    },
    {
      "hole_id": 3958,
      "led_id": 6405,
      "led_position": 260,
      "placement_id": 4377,
      "set_id": 27,
      "x": 28,
      "y": 32
    },
    {
      "hole_id": 3959,
      "led_id": 6406,
      "led_position": 261,
      "placement_id": 4378,
      "set_id": 26,
      "x": 32,
      "y": 28
    },
    {
      "hole_id": 3960,
      "led_id": 6407,
      "led_position": 262,
      "placement_id": 4379,
      "set_id": 26,
      "x": 32,
      "y": 36
    },
    {
      "hole_id": 3961,
      "led_id": 6408,
      "led_position": 263,
      "placement_id": 4380,
      "set_id": 26,
      "x": 32,
      "y": 44
    },
    {
      "hole_id": 3962,
      "led_id": 6409,
      "led_position": 264,
      "placement_id": 4381,
      "set_id": 26,
      "x": 32,
      "y": 52
    },
    {
      "hole_id": 3963,
      "led_id": 6410,
      "led_position": 265,
      "placement_id": 4382,
      "set_id": 26,
      "x": 32,
      "y": 60
    },
    {
      "hole_id": 3964,
      "led_id": 6411,
      "led_position": 266,
      "placement_id": 4383,
      "set_id": 26,
      "x": 32,
      "y": 68
    },
    {
      "hole_id": 3965,
      "led_id": 6412,
      "led_position": 267,
      "placement_id": 4384,
      "set_id": 26,
      "x": 32,
      "y": 76
    },
    {
      "hole_id": 3966,
      "led_id": 6413,
      "led_position": 268,
      "placement_id": 4385,
      "set_id": 26,
      "x": 32,
      "y": 84
    },
    {
      "hole_id": 3967,
      "led_id": 6414,
      "led_position": 269,
      "placement_id": 4386,
      "set_id": 26,
      "x": 32,
      "y": 92
    },
    {
      "hole_id": 3968,
      "led_id": 6415,
      "led_position": 270,
      "placement_id": 4387,
      "set_id": 26,
      "x": 32,
      "y": 100
    },
    {
      "hole_id": 3969,
      "led_id": 6416,
      "led_position": 271,
      "placement_id": 4388,
      "set_id": 26,
      "x": 32,
      "y": 108
    },
    {
      "hole_id": 3970,
      "led_id": 6417,
      "led_position": 272,
      "placement_id": 4389,
      "set_id": 26,
      "x": 32,
      "y": 116
    },
    {
      "hole_id": 3971,
      "led_id": 6418,
      "led_position": 273,
      "placement_id": 4390,
      "set_id": 26,
      "x": 32,
      "y": 124
    },
    {
      "hole_id": 3972,
      "led_id": 6419,
      "led_position": 274,
      "placement_id": 4391,
      "set_id": 26,
      "x": 32,
      "y": 132
    },
    {
      "hole_id": 3973,
      "led_id": 6420,
      "led_position": 275,
      "placement_id": 4392,
      "set_id": 26,
      "x": 32,
      "y": 140
    },
    {
      "hole_id": 3974,
      "led_id": 6421,
      "led_position": 276,
      "placement_id": 4393,
      "set_id": 27,
      "x": 36,
      "y": 136
    },
    {
      "hole_id": 3975,
      "led_id": 6422,
      "led_position": 277,
      "placement_id": 4394,
      "set_id": 27,
      "x": 36,
      "y": 128
    },
    {
      "hole_id": 3976,
      "led_id": 6423,
      "led_position": 278,
      "placement_id": 4395,
      "set_id": 27,
      "x": 36,
      "y": 120
    },
    {
      "hole_id": 3977,
      "led_id": 6424,
      "led_position": 279,
      "placement_id": 4396,
      "set_id": 27,
      "x": 36,
      "y": 112
    },
    {
      "hole_id": 3978,
      "led_id": 6425,
      "led_position": 280,
      "placement_id": 4397,
      "set_id": 27,
      "x": 36,
      "y": 104
    },
    {
      "hole_id": 3979,
      "led_id": 6426,
      "led_position": 281,
      "placement_id": 4398,
      "set_id": 27,
      "x": 36,
      "y": 96
    },
    {
      "hole_id": 3980,
      "led_id": 6427,
      "led_position": 282,
      "placement_id": 4399,
      "set_id": 27,
      "x": 36,
      "y": 88
    },
    {
      "hole_id": 3981,
      "led_id": 6428,
      "led_position": 283,
      "placement_id": 4400,
      "set_id": 27,
      "x": 36,
      "y": 80
    },
    {
      "hole_id": 3982,
      "led_id": 6429,
      "led_position": 284,
      "placement_id": 4401,
      "set_id": 27,
      "x": 36,
      "y": 72
    },
    {
      "hole_id": 3983,
      "led_id": 6430,
      "led_position": 285,
      "placement_id": 4402,
      "set_id": 27,
      "x": 36,
      "y": 64
    },
    {
      "hole_id": 3984,
      "led_id": 6431,
      "led_position": 286,
      "placement_id": 4403,
      "set_id": 27,
      "x": 36,
      "y": 56
    },
    {
      "hole_id": 3985,
      "led_id": 6432,
      "led_position": 287,
      "placement_id": 4404,
      "set_id": 27,
      "x": 36,
      "y": 48
    },
    {
      "hole_id": 3986,
      "led_id": 6433,
      "led_position": 288,
      "placement_id": 4405,
      "set_id": 27,
      "x": 36,
      "y": 40
    },
    {
      "hole_id": 3987,
      "led_id": 6434,
      "led_position": 289,
      "placement_id": 4406,
      "set_id": 27,
      "x": 36,
      "y": 32
    },
    {
      "hole_id": 3988,
      "led_id": 6435,
      "led_position": 290,
      "placement_id": 4407,
      "set_id": 26,
      "x": 40,
      "y": 28
    },
    {
      "hole_id": 3989,
      "led_id": 6436,
      "led_position": 291,
      "placement_id": 4408,
      "set_id": 26,
      "x": 40,
      "y": 36
    },
    {
      "hole_id": 3990,
      "led_id": 6437,
      "led_position": 292,
      "placement_id": 4409,
      "set_id": 26,
      "x": 40,
      "y": 44
    },
    {
      "hole_id": 3991,
      "led_id": 6438,
      "led_position": 293,
      "placement_id": 4410,
      "set_id": 26,
      "x": 40,
      "y": 52
    },
    {
      "hole_id": 3992,
      "led_id": 6439,
      "led_position": 294,
      "placement_id": 4411,
      "set_id": 26,
      "x": 40,
      "y": 60
    },
    {
      "hole_id": 3993,
      "led_id": 6440,
      "led_position": 295,
      "placement_id": 4412,
      "set_id": 26,
      "x": 40,
      "y": 68
    },
    {
      "hole_id": 3994,
      "led_id": 6441,
      "led_position": 296,
      "placement_id": 4413,
      "set_id": 26,
      "x": 40,
      "y": 76
    },
    {
      "hole_id": 3995,
      "led_id": 6442,
      "led_position": 297,
      "placement_id": 4414,
      "set_id": 26,
      "x": 40,
      "y": 84
    },
    {
      "hole_id": 3996,
      "led_id": 6443,
      "led_position": 298,
      "placement_id": 4415,
      "set_id": 26,
      "x": 40,
      "y": 92
    },
    {
      "hole_id": 3997,
      "led_id": 6444,
      "led_position": 299,
      "placement_id": 4416,
      "set_id": 26,
      "x": 40,
      "y": 100
    },
    {
      "hole_id": 3998,
      "led_id": 6445,
      "led_position": 300,
      "placement_id": 4417,
      "set_id": 26,
      "x": 40,
      "y": 108
    },
    {
      "hole_id": 3999,
      "led_id": 6446,
      "led_position": 301,
      "placement_id": 4418,
      "set_id": 26,
      "x": 40,
      "y": 116
    },
    {
      "hole_id": 4000,
      "led_id": 6447,
      "led_position": 302,
      "placement_id": 4419,
      "set_id": 26,
      "x": 40,
      "y": 124
    },
    {
      "hole_id": 4001,
      "led_id": 6448,
      "led_position": 303,
      "placement_id": 4420,
      "set_id": 26,
      "x": 40,
      "y": 132
    },
    {
      "hole_id": 4002,
      "led_id": 6449,
      "led_position": 304,
      "placement_id": 4421,
      "set_id": 26,
      "x": 40,
      "y": 140
    }
  ],
  "revision": "kilter:7:8:17:f0d70b3db9a6",
  "roles": [
    {
      "fullName": "Start",
      "ledColor": "00FF00",
      "name": "start",
      "screenColor": "00DD00",
      "semantic": "start",
      "sourceId": 42
    },
    {
      "fullName": "Middle",
      "ledColor": "00FFFF",
      "name": "middle",
      "screenColor": "00FFFF",
      "semantic": "middle",
      "sourceId": 43
    },
    {
      "fullName": "Finish",
      "ledColor": "FF00FF",
      "name": "finish",
      "screenColor": "FF00FF",
      "semantic": "finish",
      "sourceId": 44
    },
    {
      "fullName": "Foot Only",
      "ledColor": "FFA500",
      "name": "foot",
      "screenColor": "FFA500",
      "semantic": "foot-only",
      "sourceId": 45
    }
  ],
  "sourceSha256": "32b2663c7e699708dc3983d6acf8eff5dd8d458530c680c50ce7f6719c61235f",
  "totalBySet": {
    "26": 234,
    "27": 238
  },
  "totalScoped": 472
} as const;
